import {
  faChevronRight,
  faHeadphones,
  faBagShopping,
  faTableList,
  faTruck,
  faUser,
  faLocationDot,
  faChevronDown,
  faArrowDownWideShort,
  faTablet,
  faArrowUpWideShort,
  faArrowLeft,
  faArrowRight,
  faStar,
  faTelevision,
  faCamera,
  faLaptopCode,
  faMobilePhone,
  faPlug,
  faGamepad,
  faGift,
  faPhone,
  faCartPlus,
  faShieldAlt,
  faShieldHalved,
  faTrash,
  faFire,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const iconMap: any = {
  faChevronRight,
  faHeadphones,
  faBagShopping,
  faMobilePhone,
  faTableList,
  faTruck,
  faUser,
  faLocationDot,
  faChevronDown,
  faArrowDownWideShort,
  faArrowUpWideShort,
  faTablet,
  faTelevision,
  faCamera,
  faLaptopCode,
  faArrowLeft,
  faArrowRight,
  faStar,
  faPlug,
  faGamepad,
  faGift,
  faPhone,
  faCartPlus,
  faShieldHalved,
  faTrash,
  faFire,
};

export const IconComponent = ({ iconName, style }: any) => {
  const icon = iconMap[iconName];
  return <FontAwesomeIcon icon={icon} style={style} />;
};
